#!/bin/bash
# Lemonbar config

# Appearance
panel_fifo="/tmp/lemonbar_${USER}"
width=$(xrandr | grep "current" | awk '{print $8a}')

iconfont="-misc-fontawesome-medium-r-normal-*-12-0-0-0-p-0-iso10646-1" 
font="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-iso10646-1"
